services:
  postgres:
    image: postgres:15-alpine # Используем alpine-версию, она весит меньше и работает быстрее
    container_name: imperia_pizza_db
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: qwerka00
      POSTGRES_DB: imperia_pizza_db
    ports:
      - "5432:5432" # Прокидываем порт из контейнера (правый) на твой локальный хост (левый)
    volumes:
      - pgdata:/var/lib/postgresql/data # Сохраняем данные БД на диск, чтобы они не исчезли при удалении контейнера
    restart: unless-stopped # Автоматический перезапуск при падении

volumes:
  pgdata: # Объявление тома для хранения данных